// File: scripts/generatePaths.ts
// Version: 1.0.0
// Description: Scans the 'processed' directory to automatically generate the
// src/features/yin/data/paths/index.ts file, creating the app's table of contents.

import fs from 'fs/promises';
import path from 'path';

const PROCESSED_DIR = path.resolve(process.cwd(), 'src/features/yin/data/lessons/processed');
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/features/yin/data/paths/index.ts');

// Helper function to convert kebab-case to Title Case
function toTitleCase(str: string) {
    return str.replace(/-/g, ' ').replace(/\b\w/g, char => char.toUpperCase());
}

async function generatePathsFile() {
    console.log('🏗️  Generating paths file from processed lessons...');
    const pathData: { [pathName: string]: any } = {};

    const pathDirs = await fs.readdir(PROCESSED_DIR, { withFileTypes: true });

    for (const pathDir of pathDirs) {
        if (!pathDir.isDirectory()) continue;
        const pathName = pathDir.name;
        if (!pathData[pathName]) {
            pathData[pathName] = { id: pathName, title: toTitleCase(pathName), chapters: {} };
        }

        const chapterDirs = await fs.readdir(path.join(PROCESSED_DIR, pathName), { withFileTypes: true });
        for (const chapterDir of chapterDirs) {
            if (!chapterDir.isDirectory()) continue;
            const chapterName = chapterDir.name;
            const lessons = [];

            const lessonFiles = await fs.readdir(path.join(PROCESSED_DIR, pathName, chapterName));
            for (const lessonFile of lessonFiles) {
                if (lessonFile.endsWith('.json')) {
                    const lessonJson = await fs.readFile(path.join(PROCESSED_DIR, pathName, chapterName, lessonFile), 'utf-8');
                    lessons.push(JSON.parse(lessonJson));
                }
            }
            
            // Sort lessons by the 'order' property
            lessons.sort((a, b) => a.order - b.order);

            pathData[pathName].chapters[chapterName] = {
                id: `${pathName}-${chapterName}`,
                title: toTitleCase(chapterName),
                description: `An exploration of ${toTitleCase(chapterName)}.`,
                lessons,
            };
        }
    }

    // --- Generate the TypeScript file content ---
    let fileContent = `// Generated by scripts/generatePaths.ts - DO NOT EDIT MANUALLY\n`;
    fileContent += `import { Lesson } from '../../types/lesson.types';\n\n`;
    // ... (Add interface definitions: PathContent, ChapterContent, LessonReference) ...
    fileContent += `
function createPlaceholderLesson(id: string, title: string): Lesson {
  return { id, title, subtitle: 'Content coming soon', duration: 10, xpReward: 30, objectives: [], sections: [] };
}

function createNotionLessonReference(lessonData: any): LessonReference {
    return {
        id: lessonData.id,
        title: lessonData.title,
        chapterNumber: 1, // You could enhance this if needed
        lessonNumber: lessonData.order,
        filename: lessonData.id,
        load: () => Promise.resolve(createPlaceholderLesson(lessonData.id, lessonData.title)),
    };
}
`;

    for (const pathName in pathData) {
        const p = pathData[pathName];
        fileContent += `\nexport const ${pathName.replace(/-/g, '_')}Path: PathContent = {\n`;
        fileContent += `  id: '${p.id}',\n  title: '${p.title}',\n  chapters: [\n`;
        
        Object.values(p.chapters).forEach((chap: any) => {
            fileContent += `    {\n      id: '${chap.id}',\n      title: '${chap.title}',\n      description: '${chap.description}',\n      lessons: [\n`;
            chap.lessons.forEach((l: any) => {
                fileContent += `        createNotionLessonReference(${JSON.stringify({id: l.id, title: l.title, order: l.order})}),\n`;
            });
            fileContent += `      ]\n    },\n`;
        });

        fileContent += `  ]\n};\n`;
    }
    
    // Add master registry
    fileContent += `\nexport const pathsContentRegistry: Record<string, PathContent> = {\n`;
    for (const pathName in pathData) {
        fileContent += `  '${pathName}': ${pathName.replace(/-/g, '_')}Path,\n`;
    }
    fileContent += `};\n`;

    await fs.writeFile(OUTPUT_FILE, fileContent);
    console.log(`✅ Successfully generated and saved to ${path.relative(process.cwd(), OUTPUT_FILE)}`);
}

generatePathsFile();
