// File: scripts/generatePaths.ts
// Version: 2.0.0 - Generates comprehensive path index from processed lessons

import fs from 'fs/promises';
import path from 'path';

const PROCESSED_DIR = path.resolve(process.cwd(), 'src/features/yin/data/lessons/processed');
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/features/yin/data/paths/generated-index.ts');

// Helper to convert kebab-case to Title Case
function toTitleCase(str: string): string {
  return str.replace(/-/g, ' ').replace(/\b\w/g, char => char.toUpperCase());
}

interface ProcessedLesson {
  id: string;
  title: string;
  path: string;
  chapter: string;
  order: number;
  sections: any[];
}

interface ChapterData {
  id: string;
  title: string;
  description: string;
  lessons: ProcessedLesson[];
}

interface PathData {
  id: string;
  title: string;
  chapters: ChapterData[];
}

async function generatePathsFile() {
  console.log('🏗️  Generating comprehensive paths index from processed lessons...\n');
  
  const pathsData: Record<string, PathData> = {};
  const lessonIndex: Record<string, { path: string; chapter: string }> = {};
  
  try {
    // Read all path directories
    const pathDirs = await fs.readdir(PROCESSED_DIR, { withFileTypes: true });
    
    for (const pathDir of pathDirs) {
      if (!pathDir.isDirectory()) continue;
      
      const pathId = pathDir.name;
      console.log(`📂 Processing path: ${pathId}`);
      
      const pathData: PathData = {
        id: pathId,
        title: toTitleCase(pathId),
        chapters: []
      };
      
      // Read all chapter directories in this path
      const chapterPath = path.join(PROCESSED_DIR, pathId);
      const chapterDirs = await fs.readdir(chapterPath, { withFileTypes: true });
      
      for (const chapterDir of chapterDirs) {
        if (!chapterDir.isDirectory()) continue;
        
        const chapterId = chapterDir.name;
        console.log(`  📄 Processing chapter: ${chapterId}`);
        
        const chapterData: ChapterData = {
          id: `${pathId}-${chapterId}`,
          title: toTitleCase(chapterId),
          description: `Explore the depths of ${toTitleCase(chapterId)}`,
          lessons: []
        };
        
        // Read all lesson files in this chapter
        const lessonPath = path.join(chapterPath, chapterId);
        const lessonFiles = await fs.readdir(lessonPath);
        
        for (const lessonFile of lessonFiles) {
          if (!lessonFile.endsWith('.json')) continue;
          
          const filePath = path.join(lessonPath, lessonFile);
          const content = await fs.readFile(filePath, 'utf-8');
          const lessonData = JSON.parse(content) as ProcessedLesson;
          
          console.log(`    ✅ Found lesson: ${lessonData.title} (order: ${lessonData.order})`);
          
          chapterData.lessons.push(lessonData);
          
          // Add to lesson index for quick lookups
          lessonIndex[lessonData.id] = {
            path: pathId,
            chapter: chapterId
          };
        }
        
        // Sort lessons by order
        chapterData.lessons.sort((a, b) => (a.order || 999) - (b.order || 999));
        
        if (chapterData.lessons.length > 0) {
          pathData.chapters.push(chapterData);
        }
      }
      
      // Sort chapters by the order of their first lesson
      pathData.chapters.sort((a, b) => {
        const aOrder = a.lessons[0]?.order || 999;
        const bOrder = b.lessons[0]?.order || 999;
        return aOrder - bOrder;
      });
      
      if (pathData.chapters.length > 0) {
        pathsData[pathId] = pathData;
      }
    }
    
    // Generate the TypeScript file
    let fileContent = `// File: src/features/yin/data/paths/generated-index.ts
// Auto-generated by scripts/generatePaths.ts - DO NOT EDIT MANUALLY
// Last generated: ${new Date().toISOString()}

export interface GeneratedLesson {
  id: string;
  title: string;
  path: string;
  chapter: string;
  order: number;
  duration?: number;
  xpReward?: number;
}

export interface GeneratedChapter {
  id: string;
  title: string;
  description: string;
  lessons: GeneratedLesson[];
}

export interface GeneratedPath {
  id: string;
  title: string;
  chapters: GeneratedChapter[];
}

// Path content registry with all processed lessons
export const generatedPathsRegistry: Record<string, GeneratedPath> = ${JSON.stringify(pathsData, null, 2)};

// Lesson index for quick path/chapter lookups
export const lessonPathIndex: Record<string, { path: string; chapter: string }> = ${JSON.stringify(lessonIndex, null, 2)};

// Helper to get chapters for a specific path
export function getChaptersForPath(pathId: string): GeneratedChapter[] {
  const path = generatedPathsRegistry[pathId];
  return path ? path.chapters : [];
}

// Helper to get all lesson IDs for a path
export function getLessonIdsForPath(pathId: string): string[] {
  const path = generatedPathsRegistry[pathId];
  if (!path) return [];
  
  return path.chapters.flatMap(chapter => 
    chapter.lessons.map(lesson => lesson.id)
  );
}

// Helper to find a lesson's location
export function findLessonLocation(lessonId: string): { path: string; chapter: string } | null {
  return lessonPathIndex[lessonId] || null;
}
`;
    
    // Write the generated file
    await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
    await fs.writeFile(OUTPUT_FILE, fileContent);
    
    // Summary
    console.log('\n📊 Generation Summary:');
    console.log(`   Paths processed: ${Object.keys(pathsData).length}`);
    console.log(`   Total chapters: ${Object.values(pathsData).reduce((sum, p) => sum + p.chapters.length, 0)}`);
    console.log(`   Total lessons indexed: ${Object.keys(lessonIndex).length}`);
    console.log(`\n✅ Successfully generated: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
    
  } catch (error) {
    console.error('❌ Error generating paths file:', error);
    process.exit(1);
  }
}

// Run the generator
generatePathsFile();